### ISSUE TITLE
How to run / build after checkout?

### ISSUE THREAD

**Issue by gloeglm** [RefugeesOnRails/website#1]
Could somebody add some basic instructions on how to run this to the readme?

I am on Windows with Cygwin shell, ruby version 

$ ruby -version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-cygwin]

**Comment by sixofhearts** [comment]
Yep, it's in the README now: https://github.com/RefugeesOnRails/website/blob/master/README.md
